parameters:
    link_value_mobile_notif.client.client_collection.class:             'LinkValue\MobileNotifBundle\Client\ClientCollection'
    link_value_mobile_notif.profiler.client_profiler.class:             'LinkValue\MobileNotifBundle\Profiler\ClientProfiler'
    link_value_mobile_notif.data_collector.client_data_collector.class: 'LinkValue\MobileNotifBundle\DataCollector\ClientDataCollector'

services:
    link_value_mobile_notif.clients:
        class:     '%link_value_mobile_notif.client.client_collection.class%'

    link_value_mobile_notif.profiler.client_profiler:
        class:     '%link_value_mobile_notif.profiler.client_profiler.class%'
        arguments: [ '@debug.stopwatch' ]

    link_value_mobile_notif.data_collector.client_data_collector:
        class:     '%link_value_mobile_notif.data_collector.client_data_collector.class%'
        arguments: [ '@link_value_mobile_notif.profiler.client_profiler' ]
        tags:
            -   name:     'data_collector'
                id:       'link_value_mobile_notif'
                template: 'LinkValueMobileNotifBundle:Toolbar:client_data_collector'
